# data folder
data_folder: datasets/recon  # path to the dataset

# image size
image_size: [85, 64] # width, height

# result folder
result_dirs:
#  gnm: logs/gnm/gnm_eval_traj_dist_pred_2023_06_23_17_18_48/result/recon_test/epoch10/trajectory_distance_prediction
##  scrl_mc_logit_sum: logs/stable_contrastive_rl/stable_contrastive_rl_eval_traj_dist_pred_2023_06_23_18_06_31/result/recon_test/epoch10/trajectory_distance_prediction  # dummy waypoint
#  scrl_mc_logit_sum: logs/stable_contrastive_rl/stable_contrastive_rl_eval_traj_dist_pred_2023_06_26_14_48_58/result/recon_test/epoch10/trajectory_distance_prediction  # predicted waypoint
##  scrl_td_logit_sum: logs/stable_contrastive_rl/stable_contrastive_rl_eval_traj_dist_pred_2023_06_23_18_06_56/result/recon_test/epoch10/trajectory_distance_prediction  # dummy waypoint
#  scrl_td_logit_sum: logs/stable_contrastive_rl/stable_contrastive_rl_eval_traj_dist_pred_2023_06_26_14_49_37/result/recon_test/epoch10/trajectory_distance_prediction  # predicted waypoint
##  scrl_mc_close_logit_diff: logs/stable_contrastive_rl/stable_contrastive_rl_eval_traj_dist_pred_2023_06_23_17_24_35/result/recon_test/epoch10/trajectory_distance_prediction  # dummy waypoint
#  scrl_mc_close_logit_diff: logs/stable_contrastive_rl/stable_contrastive_rl_eval_traj_dist_pred_2023_06_26_14_50_10/result/recon_test/epoch10/trajectory_distance_prediction  # predicted waypoint
##  scrl_td_close_logit_diff: logs/stable_contrastive_rl/stable_contrastive_rl_eval_traj_dist_pred_2023_06_23_17_25_41/result/recon_test/epoch10/trajectory_distance_prediction  # dummy waypoint
#  scrl_td_close_logit_diff: logs/stable_contrastive_rl/stable_contrastive_rl_eval_traj_dist_pred_2023_06_26_14_50_54/result/recon_test/epoch10/trajectory_distance_prediction  # predicted waypoint
##  scrl_mc_far_logit_diff: logs/stable_contrastive_rl/stable_contrastive_rl_eval_traj_dist_pred_2023_06_23_17_26_48/result/recon_test/epoch10/trajectory_distance_prediction  # dummy waypoint
#  scrl_mc_far_logit_diff: logs/stable_contrastive_rl/stable_contrastive_rl_eval_traj_dist_pred_2023_06_26_14_51_50/result/recon_test/epoch10/trajectory_distance_prediction  # predicted waypoint
##  scrl_td_far_logit_diff: logs/stable_contrastive_rl/stable_contrastive_rl_eval_traj_dist_pred_2023_06_23_17_27_37/result/recon_test/epoch10/trajectory_distance_prediction  # dummy waypoint
#  scrl_td_far_logit_diff: logs/stable_contrastive_rl/stable_contrastive_rl_eval_traj_dist_pred_2023_06_26_14_53_06/result/recon_test/epoch10/trajectory_distance_prediction  # predicted waypoint
##  scrl_mc_mi_diff: logs/stable_contrastive_rl/stable_contrastive_rl_eval_traj_dist_pred_2023_06_23_17_29_14/result/recon_test/epoch10/trajectory_distance_prediction  # dummy waypoint
#  scrl_mc_mi_diff: logs/stable_contrastive_rl/stable_contrastive_rl_eval_traj_dist_pred_2023_06_26_14_53_45/result/recon_test/epoch10/trajectory_distance_prediction  # predicted waypoint
##  scrl_td_mi_diff: logs/stable_contrastive_rl/stable_contrastive_rl_eval_traj_dist_pred_2023_06_23_17_30_25/result/recon_test/epoch10/trajectory_distance_prediction  # dummy waypoint
##  scrl_td_mi_diff: logs/stable_contrastive_rl/stable_contrastive_rl_eval_traj_dist_pred_2023_06_26_14_54_29/result/recon_test/epoch10/trajectory_distance_prediction  # predicted waypoint
#  # test gps
#  scrl_td_mi_diff: logs/stable_contrastive_rl/stable_contrastive_rl_eval_traj_dist_pred_2023_06_28_14_35_02/result/recon_test/epoch10/trajectory_distance_prediction  # predicted waypoint

  # use training set
#  gnm: logs/gnm/gnm_eval_traj_dist_pred_2023_06_28_23_30_25/result/recon_test/epoch10/trajectory_distance_prediction
#  scrl_mc_sorting: logs/stable_contrastive_rl/stable_contrastive_rl_eval_traj_dist_pred_2023_06_28_23_44_33/result/recon_test/epoch10/trajectory_distance_prediction
#  scrl_td_sorting: logs/stable_contrastive_rl/stable_contrastive_rl_eval_traj_dist_pred_2023_06_28_23_45_07/result/recon_test/epoch10/trajectory_distance_prediction

  # sanity check:
  gnm: logs/gnm/gnm_eval_traj_dist_pred_2023_06_29_23_34_34/result/recon_test/epoch10/trajectory_distance_prediction
  scrl_mc_sorting: logs/stable_contrastive_rl/stable_contrastive_rl_eval_traj_dist_pred_2023_06_29_23_32_34/result/recon_test/epoch30/trajectory_distance_prediction
  scrl_td_sorting: logs/stable_contrastive_rl/stable_contrastive_rl_eval_traj_dist_pred_2023_06_29_23_32_34/result/recon_test/epoch30/trajectory_distance_prediction

# save folder
save_dir: logs/visualize_trajectory_distance_prediction
