project_name: gnm
run_name: gnm_test

# training setup
use_wandb: True # set to false if you don't want to log to wandb
train: supervised
batch_size: 400
eval_batch_size: 400
epochs: 10
gpu_ids: [0, 1, 2, 3] # list of gpu ids to use
num_workers: 16
lr: 5e-4
optimizer: adam
seed: 0

# model params
model_type: gnm
obs_encoding_size: 1024
goal_encoding_size: 1024

# normalization for the action space
normalize: True

# context
context_type: temporal
context_size: 5

# tradeoff between action and distance prediction loss
alpha: 0.5

# distance bounds for distance and action and distance predictions 
distance:
  min_dist_cat: 0
  max_dist_cat: 1000
action:
  min_dist_cat: 2
  max_dist_cat: 1000

# action output params
len_traj_pred: 5
learn_angle: True

# dataset specific parameters
image_size: [85, 64] # width, height
datasets:
  recon:
    data_folder: datasets/recon # path to the dataset
    train: gnm_train/data/data_splits/recon/train/ # path to the train dir with traj_names.txt
    test: gnm_train/data/data_splits/recon/test/ # path to the test dir with traj_names.txt
    end_slack: 3 # because many trajectories end in collisions
    goals_per_obs: 1 # how many goals are sampled per observation
    negative_mining: True # negative mining from the ViNG paper (Shah et al.)

# logging stuff
print_log_freq: 500 # in iterations
image_log_freq: 1000 # in iterations
num_images_log: 8 # number of images to log in a logging iteration
pairwise_test_freq: 1 # in epochs
