project_name: gnm
run_name: gnm_eval_traj_dist_pred

# training setup
use_wandb: False # set to false if you don't want to log to wandb
eval: supervised
traj_batch_size: 1  # batch size for number of trajectories
traj_eval_batch_size: 1  # eval batch size for number of trajectories
batch_size: 32
eval_batch_size: 32
epochs: 1
gpu_ids: [1] # list of gpu ids to use
num_workers: 16
lr: 5e-4
optimizer: adam
seed: 0

# model params
model_type: gnm
obs_encoding_size: 1024
goal_encoding_size: 1024

# normalization for the action space
normalize: True

# context
context_type: temporal
context_size: 0

# tradeoff between action and distance prediction loss
alpha: 0.5

# action output params
len_traj_pred: 5
learn_angle: True

# dataset specific parameters
image_size: [85, 64] # width, height
datasets:
  recon:
    data_folder: datasets/recon # path to the dataset
#    test: gnm_train/data/data_splits/recon_traj_dist_pred/test/ # folder to read trajectory names
    test_traj_names: [
#      "jackal_2019-08-06-16-16-07_15_r02",
#      "jackal_2019-08-08-16-52-33_10_r00",
#      "jackal_2019-09-19-15-57-48_33_r00",
#      "jackal_2019-08-02-17-37-37_61_r02",
#      "jackal_2019-08-06-15-08-36_7_r00",
#      "jackal_2019-09-19-15-57-48_33_r00",
      # use data from training set
      # scene 1
      jackal_2019-08-29-14-28-12_8_r02,
      jackal_2019-08-29-14-40-17_5_r01,
      jackal_2019-08-08-17-01-33_19_r02,
      jackal_2019-09-09-14-44-00_18_r00,
      jackal_2019-08-08-13-24-29_3_r00,
      jackal_2019-09-12-18-11-38_2_r02,
      jackal_2019-09-17-16-39-46_0_r01,
      jackal_2019-08-29-16-16-35_2_r00,
      jackal_2019-09-12-15-30-34_37_r00,
      jackal_2019-09-09-15-53-33_40_r03,
      jackal_2019-08-13-15-43-57_1_r01,
      jackal_2019-08-27-16-23-56_9_r00,
      jackal_2019-09-19-16-03-40_2_r00,
      jackal_2019-08-13-17-03-54_2_r02,
      jackal_2019-08-08-14-43-03_5_r03,
      jackal_2019-08-20-17-11-13_2_r01,
      jackal_2020-01-04-15-30-11_9_r00,
      jackal_2019-08-20-17-37-16_0_r00,
      jackal_2019-08-27-14-43-05_18_r00,
      jackal_2019-12-19-12-25-57_1_r00,
      jackal_2019-08-08-16-04-01_6_r02,
      jackal_2019-08-29-14-55-32_11_r01,
      jackal_2019-12-19-14-37-04_0_r00,
      jackal_2019-08-15-16-11-21_28_r02,
      jackal_2019-08-29-17-04-25_5_r02,

      # scene 2
      jackal_2019-12-19-12-25-57_1_r00,
      jackal_2019-12-19-16-08-09_10_r03,
      jackal_2019-12-21-14-22-04_13_r00,
      jackal_2020-01-03-14-19-30_7_r00,
    ]
    # goal node index in the trajectory (if -1, then the goal node is the last node in the trajectory)
    goal_idxs: [
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
      -1,
#      -1,
#      -1,
#      -1
    ]
    end_slack: 3 # because many trajectories end in collisions
    subsampling_spacing: 5 # sampling trajectory points every "subsampling_spacing" timestep

# evalulation mode
eval_waypoint: False
eval_pairwise_dist_pred: False
eval_traj_dist_pred: True

# pre-trained model
#load_run: gnm/gnm_test_2023_04_29_22_39_38  # random checkpoint for testing

# GNM distance prediction drop-off
#load_run: gnm/gnm_small_2023_05_25_14_17_06  # dist_max_cat = 20
#load_run: gnm/gnm_small_2023_05_25_14_17_12  # dist_max_cat = 25
#load_run: gnm/gnm_small_2023_05_25_14_17_26  # dist_max_cat = 30

# GNM model trained on the full dataset
#load_run: gnm/gnm_debug_2023_03_10_20_05_22
# GNM model trained on the full recon dataset with no context and full trajectory
load_run: gnm/gnm_test_2023_06_10_20_53_15

# logging stuff
print_log_freq: 5 # in iterations
#image_log_freq: 25 # in iterations
image_log_freq: 2500 # in iterations
save_traj_dist_pred_freq: 1 # in iterations
